### PR TITLE
Add Logotype

### PR DESCRIPTION
**Pull request by richardbmx**

### CODE REVIEW

**Comment by abargnesi** [comment]
🎉

This looks good to me but I think you should add your contact information and any attribution license details to go along with your work.

That way if people like the logo they can contact you or find your other works.

Also should rantly link the icon from your fork or can that be changed after merge?

**Comment by richardbmx** [comment]
They can change it without problems .. in the logo theme I have left a folder of google drive with all the necessary files to use the logo

**Comment by abargnesi** [comment]
Thanks! This looks great.

**Comment by richardbmx** [comment]
Here I annex again the google folder with all the files

[Google Drive](https://drive.google.com/open?id=11WXqhV5yxOyTkp-MwrqfLbJl7YQhQ4H7)

**Pull request merged**
